### ISSUE TITLE
Support React v19

### ISSUE THREAD

**Issue by laakal** [elrumordelaluz/reactour#659]
We are unable to upgrade to React 19  because `reactour` gives the following error.

```js
 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
 1. You might have mismatching versions of React and the renderer (such as React DOM)
 2. You might be breaking the Rules of Hooks
 3. You might have more than one copy of React in the same app
 See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
 TypeError: Cannot read properties of null (reading 'useState')
     at useState (../node_modules/@reactour/tour/node_modules/react/cjs/react.development.js:1622:21)
     at TourProvider (../node_modules/@reactour/tour/dist/index.js:971:58)
  ⨯ Internal error: TypeError: Cannot read properties of null (reading 'useState')
     at useState (../node_modules/@reactour/tour/node_modules/react/cjs/react.development.js:1622:21)
     at TourProvider (../node_modules/@reactour/tour/dist/index.js:971:58)
     at react-stack-bottom-frame (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:8798:18)
     at renderWithHooks (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:4722:19)
     at renderElement (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:5157:23)
     at retryNode (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:5805:22)
     at renderNodeDestructive (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:5631:11)
     at renderNode (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:6181:18)
     at renderChildrenArray (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:6066:9)
     at retryNode (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:5818:13)
     at renderNodeDestructive (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:5631:11)
     at renderElement (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:5535:15)
     at retryNode (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:5805:22)
     at renderNodeDestructive (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:5631:11)
     at finishFunctionComponent (../node_modules/react-dom/cjs/react-dom-server.edge.development.js:4766:13)

```

**Comment by dillonrowan** [comment]
Is there a timeline on when react tour will support react 19?

**Comment by Porok12** [comment]
Bump

**Comment by Tommuh** [comment]
Is this fixed? Because the last release is still from 2022?

**Comment by elrumordelaluz** [comment]
> Is this fixed? Because the last release is still from 2022?

https://www.npmjs.com/package/@reactour/tour?activeTab=versions
